package data;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import com.google.auth.oauth2.GoogleCredentials;
import com.google.cloud.GcpLaunchStage.Deprecated;
import com.google.firebase.*;
import com.google.firebase.database.*;

/**
 * Creates and interacts with Firebase; handles actions used to submit, fetch, and access essays, submissions, and other parts
 * 
 * @author Alex Wang, John Shelby for assistance in Firebase logic
 *
 */
public class DatabaseModifier {
	
	private DatabaseReference classroomsRef;
	private DatabaseChangeListener DBChangeListener;

	public DatabaseModifier() {
		setupDatabase();
	}
	
	/**
	 * Creates a Database Reference and sets up necessary Firebase options
	 */
	public void setupDatabase() {
		FileInputStream refreshToken;
		
		try {
			refreshToken = new FileInputStream("GradeMeFirebaseKey.json");
			
			FirebaseOptions options = FirebaseOptions.builder()
					.setCredentials(GoogleCredentials.fromStream(refreshToken))
				    .setDatabaseUrl("https://grademe-e5a48-default-rtdb.firebaseio.com/")
				    .build();

			FirebaseApp.initializeApp(options);
			
			DatabaseReference database = FirebaseDatabase.getInstance().getReference();
			
			// structure = root/classrooms
			classroomsRef = database.child("classrooms");
			
			
			// always keep local variables synced up
			DBChangeListener = new DatabaseChangeListener();
			classroomsRef.addChildEventListener(DBChangeListener);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	
	/**
	 * Submit classroom to Database
	 * @param classroomSubmission Classroom object to be submitted to database root
	 * @return postID from new data path (DatabaseReference) used to retrieve data
	 */
	public String submitClassroomToDatabase(Classroom classroomSubmission) {
		String postID = null;
		
		try {
			System.out.println("submitToDatabase() called");
			DatabaseReference pushedPostRef = classroomsRef.push();
			pushedPostRef.setValueAsync(classroomSubmission);
			
			
			// get unique key generated by push()
			postID = pushedPostRef.getKey();
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return postID;
	}
	
	/**
	 * Submit Student object to known Classroom in Database
	 * @param student Student object to be added
	 * @param classroomID postID of the classroom (returned by submitClassroomToDatabase())
	 */
	@Deprecated
	public void addStudentToClassroom(Student student, String classroomID) {
		DatabaseReference classroomRef = classroomsRef.child(classroomID);
		Map<String, Object> studentAddition = new HashMap<>();
		studentAddition.put("students/1", student);
		
//		classroomRef.child("students").child("groupA"). addValueEventListener(...);
		
		// current bug - code does not add student obejct to a list of students -- instead it replaces all under students/
		
		classroomRef.updateChildrenAsync(studentAddition);	
	}
	
	/**
	 * Get the local/cached version of the Classroom object (should be synced with Firebase)
	 * @return most up-to-date version of Classroom object
	 */
	public Classroom getClassroom() {
		return DBChangeListener.getClassroom();
	}
	
	public ArrayList<Classroom> getClassrooms() {
		return DBChangeListener.getClassrooms();
	}
	
}
