package ServerClient;

import java.io.FileInputStream;
import java.io.IOException;

import com.google.auth.oauth2.GoogleCredentials;
import com.google.firebase.*;
import com.google.firebase.database.*;

import data.Submission;

/**
 * Creates and interacts with Firebase; handles actions used to submit, fetch, and access essays, submissions, and other parts
 * 
 * @author Alex Wang, John Shelby for assistance in Firebase logic
 *
 */
public class DatabaseModifier {
	
	private DatabaseReference postsRef;

	public DatabaseModifier() {
		setupDatabase();
	}
	
	/**
	 * Creates a Database Reference and sets up necessary Firebase options
	 */
	public void setupDatabase() {
		FileInputStream refreshToken;
		
		try {
			
			System.out.println("got here2");
			refreshToken = new FileInputStream("GradeMeFirebaseKey.json");
			
			FirebaseOptions options = FirebaseOptions.builder()
					.setCredentials(GoogleCredentials.fromStream(refreshToken))
				    .setDatabaseUrl("https://grademe-e5a48-default-rtdb.firebaseio.com/")
				    .build();

			FirebaseApp.initializeApp(options);
			
			System.out.println("got here");
			
			DatabaseReference database = FirebaseDatabase.getInstance().getReference();
			postsRef = database.child("posts");

				// postsRef.addChildEventListener(new DatabaseChangeListener());
				
				System.out.println("got here3");
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	
	/**
	 * Submit submission to Database
	 * @param studentSubmission Submission object to be submitted
	 * @return postID from new data path (DatabaseReference) used to retrieve data
	 */
	public String submitToDatabase(Submission studentSubmission) {
		String postID = null;
		
		try {
			System.out.println("submitToDatabase() called");
			DatabaseReference pushedPostRef = postsRef.push();
			// pushedPostRef.setValueAsync(studentSubmission);
			pushedPostRef.setValueAsync("TEST");
			
			// get unique key generated by push()
			postID = pushedPostRef.getKey();
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return postID;
	}
}
